full_name = "Rafy Benjamin"
description = "Rafy is a software Engineer with great passion, Currently working with TF-Chain team"
why_threefold = "Threefold and I have same goals of giving freedom and control back to the people, and it has lots of bright minds I'm so proud to work/learn from them on daily basis."
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
